displayName=Click2Minimize
author=Click2Minimize Team
description=Minimizes the game client when you click on specific skilling spots.
tags=afk,minimize,netflix
version=
plugins=com.click2minimize.Click2MinimizePlugin
build=standard